package com.gayatriladieswears.app.Model

import com.google.gson.annotations.SerializedName
import java.math.BigInteger

data class OrderShip(
    @SerializedName("order_id")var order_id:String? = null,
    @SerializedName("order_date")var order_date:String? = null,
    @SerializedName("pickup_location")var pickup_location:String? = null,
    @SerializedName("channel_id")var channel_id:String? = null,
    @SerializedName("comment")var comment:String? = null,
    @SerializedName("reseller_name")var reseller_name:String? = null,
    @SerializedName("company_name")var company_name:String? = null,
    @SerializedName("billing_customer_name")var billing_customer_name:String? = null,
    @SerializedName("billing_last_name")var billing_last_name:String? = null,
    @SerializedName("billing_address")var billing_address:String? = null,
    @SerializedName("billing_address_2")var billing_address_2:String? = null,
    @SerializedName("billing_city")var billing_city:String? = null,
    @SerializedName("billing_pincode")var billing_pincode:Int? = null,
    @SerializedName("billing_state")var billing_state:String? = null,
    @SerializedName("billing_country")var billing_country:String? = null,
    @SerializedName("billing_email")var billing_email:String? = null,
    @SerializedName("billing_phone")var billing_phone:Long? = null,
    @SerializedName("billing_alternate_phone")var billing_alternate_phone:String? = null,
    @SerializedName("shipping_is_billing")var shipping_is_billing:Boolean? = null,
    @SerializedName("shipping_customer_name")var shipping_customer_name:String? = null,
    @SerializedName("shipping_last_name")var shipping_last_name:String? = null,
    @SerializedName("shipping_address")var shipping_address:String? = null,
    @SerializedName("shipping_address_2")var shipping_address_2:String? = null,
    @SerializedName("billing_isd_code")var billing_isd_code:String? = null,
    @SerializedName("shipping_city")var shipping_city:String? = null,
    @SerializedName("shipping_pincode")var shipping_pincode:Int? = null,
    @SerializedName("shipping_country")var shipping_country:String? = null,
    @SerializedName("shipping_state")var shipping_state:String? = null,
    @SerializedName("shipping_email")var shipping_email:String? = null,
    @SerializedName("shipping_phone")var shipping_phone: Long? = null,
    @SerializedName("longitude")var longitude:String? = null,
    @SerializedName("latitude")var latitude:String? = null,
    @SerializedName("order_items")var order_items:ArrayList<OrderShipItem>? = ArrayList<OrderShipItem>(),
    @SerializedName("payment_method")var payment_method:String? = null,
    @SerializedName("shipping_charges")var shipping_charges:Int? = null,
    @SerializedName("giftwrap_charges")var giftwrap_charges:Int? = null,
    @SerializedName("transaction_charges")var transaction_charges:Int? = null,
    @SerializedName("total_discount")var total_discount:Int? = null,
    @SerializedName("sub_total")var sub_total:Int? = null,
    @SerializedName("length")var length:Float? = null,
    @SerializedName("breadth")var breadth:Float? = null ,
    @SerializedName("height")var height:Float? = null,
    @SerializedName("weight")var weight:Float? = null,
    @SerializedName("ewaybill_no")var ewaybill_no:String? = null,
    @SerializedName("customer_gstin")var customer_gstin:String? = null,
    @SerializedName("invoice_number")var invoice_number:String? = null,
    @SerializedName("order_type")var order_type:String? = null
)
